e:
cd \datacrunchfiles
del LineCount.txt
rem del *.csv
rem pause
call DTSToCSV DataCrunchEnrollmentLEP 1999 01
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa01.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 02
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa02.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 03
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa03.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 04
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa04.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 05
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa05.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 06
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa06.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 07
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa07.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 08
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa08.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 09
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa09.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 10
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa10.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 11
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa11.csv
call DTSToCSV DataCrunchEnrollmentLEP 1999 12
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_1999_cesa12.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 01
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa01.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 02
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa02.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 03
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa03.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 04
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa04.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 05
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa05.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 06
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa06.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 07
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa07.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 08
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa08.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 09
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa09.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 10
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa10.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 11
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa11.csv
call DTSToCSV DataCrunchEnrollmentLEP 2000 12
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2000_cesa12.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 01
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa01.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 02
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa02.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 03
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa03.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 04
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa04.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 05
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa05.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 06
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa06.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 07
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa07.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 08
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa08.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 09
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa09.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 10
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa10.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 11
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa11.csv
call DTSToCSV DataCrunchEnrollmentLEP 2001 12
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2001_cesa12.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 01
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa01.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 02
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa02.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 03
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa03.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 04
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa04.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 05
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa05.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 06
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa06.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 07
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa07.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 08
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa08.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 09
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa09.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 10
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa10.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 11
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa11.csv
call DTSToCSV DataCrunchEnrollmentLEP 2002 12
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2002_cesa12.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 01
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa01.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 02
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa02.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 03
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa03.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 04
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa04.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 05
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa05.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 06
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa06.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 07
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa07.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 08
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa08.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 09
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa09.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 10
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa10.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 11
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa11.csv
call DTSToCSV DataCrunchEnrollmentLEP 2003 12
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2003_cesa12.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 01
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa01.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 02
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa02.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 03
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa03.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 04
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa04.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 05
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa05.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 06
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa06.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 07
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa07.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 08
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa08.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 09
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa09.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 10
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa10.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 11
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa11.csv
call DTSToCSV DataCrunchEnrollmentLEP 2004 12
ren TempFileOutput.csv what_is_the_enrollment_by_student_group_english_proficiency_2004_cesa12.csv

for %%z in (*.csv) do wc -l %%z | sort >> LineCount.txt
type LineCount.txt
